import ArrowLeftIcon from '@/icons/arrowLeft';

export const menuItems = [
  {
    id: 1,
    name: 'Settings',
    route: '/settings',
    menu: true,
    icon: ArrowLeftIcon,
    feature: false,
    description: 'Configuración del perfil del usuario',
    role: ['admin', 'user'],
  },

  {
    id: 2,
    name: 'Dashboard',
    route: '/dashboard',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Dashboard',
    role: ['admin', 'user'],
  },
  {
    id: 3,
    name: 'Usuarios',
    route: '/users',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Configuración de usuarios del sistema',
    role: ['admin'],
  },
  {
    id: 7,
    name: 'Secciones',
    route: '/config-sections',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Configuración de secciones del sistema',
    role: ['admin'],
  },
  {
    id: 4,
    name: 'Contactos',
    route: '/contacts',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Contactos recibidos desde la página web',
    role: ['admin', 'user'],
  },
  {
    id: 5,
    name: 'Suscriptores',
    route: '/subscribers',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Suscripciones al newsletter recibidos desde la página web',
    role: ['admin', 'user'],
  },
  {
    id: 6,
    name: 'Secciones',
    route: '/sections',
    menu: true,
    feature: false,
    icon: ArrowLeftIcon,
    description: 'Configuración de secciones de la página web',
    role: ['admin', 'user'],
  },
];