import type { Metadata } from "next";

import "./globals.css";
import { caveat, inter } from './fonts';
import Menu from '@/components/Menu/Index';

export const metadata: Metadata = {
  title: "Delicias Gales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <link rel="icon" href="next.svg" type="image/x-icon" />
      <body
        className={`${caveat.variable} ${inter.variable} antialiased bg-custom-tertiary`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
